# Dockerfile
FROM node:22.11-alpine

# 设置工作目录
WORKDIR /app

# 安装依赖
COPY package*.json ./
RUN npm install --production

# 复制代码
COPY . .

# 创建日志目录
RUN mkdir -p /app/logs

# 运行脚本
CMD ["node", "scraper.js"]
